import { NodeType } from './types';
import type { FileNode } from './types';

export const MOCK_FILE_SYSTEM: FileNode[] = [
  {
    name: "VUE学习笔记",
    path: "VUE学习笔记",
    type: NodeType.DIRECTORY,
    children: [
      {
        name: "Welcome.md",
        path: "VUE学习笔记/Welcome.md",
        type: NodeType.FILE,
        lastModified: "2023-11-01T10:00:00Z",
        content: "# Welcome to Sakura Notes 🌸\n\nThis is a mock file used when `files.json` cannot be loaded.\n\n## Features\n- Markdown support\n- Live preview\n- Aesthetic design"
      }
    ]
  }
];

export const I18N = {
  en: {
    loading: "Loading Sakura Notes...",
    subtitle: "Frontend & Vue Learner",
    tab_latest: "Latest",
    tab_files: "Files",
    tab_lab: "Lab",
    lab_tools: "Interactive Tools",
    lab_course: "Vue Ninja Training",
    lab_reactivity: "Reactivity",
    lab_reactivity_desc: "Data binding visualizer",
    lab_lifecycle: "Lifecycle",
    lab_lifecycle_desc: "Hook execution flow",
    lab_directives: "Directives",
    lab_directives_desc: "v-if vs v-show visualizer",
    lab_quiz: "Vue Ninja Quiz",
    lab_quiz_desc: "Test your knowledge!",
    no_notes: "No personal notes found.",
    no_vue_notes: "No 'VUE学习笔记' folder found.",
    reading_notes: "Reading notes...",
    welcome_title: "Welcome Home",
    welcome_desc: "Explore your personal knowledge base.",
    welcome_tags: "Frontend Notes · Vue Docs · Life",
    on_this_page: "On this page",
    note_details: "Note Details",
    words: "Words",
    lines: "Lines",
    format: "Format",
    updated: "Updated",
    settings_title: "Settings",
    font_style: "Font Style",
    font_size: "Font Size",
    theme: "Theme",
    theme_light: "Light",
    theme_dark: "Dark",
    done: "Done",
    share_title: "Share Quote",
    scan_text: "Copy as Markdown to share",
    close: "Close",
    link_copied: "Link copied! 🌸",
    quote_copied: "Markdown quote copied! 📝",
    copy_link: "Copy Link",
    download: "Download",
    search_placeholder: "Search notes...",
    back_home: "Home",
    toast_copied: "Copied to clipboard!"
  },
  zh: {
    loading: "正在加载樱花笔记...",
    subtitle: "Frontend & Vue Learner",
    tab_latest: "最新",
    tab_files: "归档",
    tab_lab: "实验室",
    lab_tools: "交互式工具",
    lab_course: "Vue 忍者试炼",
    lab_reactivity: "响应式原理",
    lab_reactivity_desc: "数据绑定可视化",
    lab_lifecycle: "生命周期",
    lab_lifecycle_desc: "钩子执行流程",
    lab_directives: "指令实验室",
    lab_directives_desc: "v-if 与 v-show 的区别",
    lab_quiz: "Vue 忍者挑战",
    lab_quiz_desc: "测测你的 Vue 水平！",
    no_notes: "暂无笔记",
    no_vue_notes: "未找到 'VUE学习笔记' 文件夹",
    reading_notes: "读取笔记中...",
    welcome_title: "欢迎回家",
    welcome_desc: "探索你的个人知识花园",
    welcome_tags: "前端笔记 · Vue 文档 · 生活感悟",
    on_this_page: "目录",
    note_details: "笔记详情",
    words: "字数",
    lines: "行数",
    format: "格式",
    updated: "最后更新",
    settings_title: "用户设置",
    font_style: "字体风格",
    font_size: "字体大小",
    theme: "主题模式",
    theme_light: "浅色",
    theme_dark: "深色",
    done: "完成",
    share_title: "分享引用",
    scan_text: "已转换为 Markdown 格式",
    close: "关闭",
    link_copied: "链接已复制! 🌸",
    quote_copied: "引用已复制! 📝",
    copy_link: "复制链接",
    download: "下载",
    search_placeholder: "搜索笔记...",
    back_home: "首页",
    toast_copied: "已复制到剪贴板！"
  }
};