export const I18N = {
  en: {
    loading: "Loading Sakura Notes...",
    subtitle: "For every reader",
    tab_latest: "Latest",
    tab_files: "Files",
    tab_lab: "Lab",
    lab_tools: "Interactive Tools",
    lab_resources: "Learning Resources",
    lab_course: "Vue Ninja Training (Project Based)",
    lab_reactivity: "Reactivity",
    lab_reactivity_desc: "Data binding visualizer",
    lab_lifecycle: "Lifecycle",
    lab_lifecycle_desc: "Hook execution flow",
    lab_directives: "Directives",
    lab_directives_desc: "v-if vs v-show visualizer",
    lab_quiz: "Vue Ninja Quiz",
    lab_quiz_desc: "Test your knowledge!",
    no_notes: "No notes found in 'en' folder.",
    no_vue_notes: "Course notes folder not found.",
    reading_notes: "Reading notes...",
    welcome_title: "Welcome Home",
    welcome_desc: "Explore the garden of knowledge belongs to you",
    welcome_tags: "Share Notes · Learn Vue",
    on_this_page: "On this page",
    note_details: "Note Details",
    words: "Words",
    lines: "Lines",
    format: "Format",
    updated: "Updated",
    settings_title: "Settings",
    font_style: "Font Style",
    font_size: "Font Size",
    sakura_speed: "Sakura Speed",
    speed_5cm: "5cm/s (Slow)",
    speed_10cm: "10cm/s (Fast)",
    theme: "Theme",
    theme_light: "Light",
    theme_dark: "Dark",
    done: "Done",
    close: "Close",
    link_copied: "Link copied! 🌸",
    copy_link: "Copy Link",
    view_source: "View Source",
    view_render: "View Render",
    download: "Download",
    search_placeholder: "Search notes...",
    back_home: "Home",
    toast_copied: "Copied to clipboard!",
    menu_highlight: "Highlight",
    menu_underline: "Underline",
    selection_error: "Selection cannot cross paragraphs.",
  },
  zh: {
    loading: "正在加载樱花笔记...",
    subtitle: "献给所有读者",
    tab_latest: "最新",
    tab_files: "归档",
    tab_lab: "实验室",
    lab_tools: "交互式工具",
    lab_resources: "前端修炼场",
    lab_course: "Vue 实战笔记 (源码解析)",
    lab_reactivity: "响应式原理",
    lab_reactivity_desc: "数据绑定可视化",
    lab_lifecycle: "生命周期",
    lab_lifecycle_desc: "钩子执行流程",
    lab_directives: "指令实验室",
    lab_directives_desc: "v-if 与 v-show 的区别",
    lab_quiz: "Vue 忍者挑战",
    lab_quiz_desc: "随机抽取5题测试水平！",
    no_notes: "在 'zh' 文件夹下暂无笔记",
    no_vue_notes: "未找到 'VUE学习笔记' 文件夹",
    reading_notes: "读取笔记中...",
    welcome_title: "欢迎回家",
    welcome_desc: "探索属于你的知识花园",
    welcome_tags: "分享笔记 · Vue 学习",
    on_this_page: "目录",
    note_details: "笔记详情",
    words: "字数",
    lines: "行数",
    format: "格式",
    updated: "最后更新",
    settings_title: "用户设置",
    font_style: "字体风格",
    font_size: "字体大小",
    sakura_speed: "花落速度",
    speed_5cm: "秒速五厘米 (唯美)",
    speed_10cm: "秒速十厘米 (轻快)",
    theme: "主题模式",
    theme_light: "浅色",
    theme_dark: "深色",
    done: "完成",
    close: "关闭",
    link_copied: "链接已复制! 🌸",
    copy_link: "复制链接",
    view_source: "查看源码",
    view_render: "查看渲染",
    download: "下载",
    search_placeholder: "搜索笔记...",
    back_home: "首页",
    toast_copied: "已复制到剪贴板！",
    menu_highlight: "高亮",
    menu_underline: "波浪线",
    selection_error: "无法跨段落标注",
  }
};