import type { TutorialStep } from './tutorialStepsLoader'

export const STEPS: TutorialStep[] = [
  {
    id: 'js:theme',
    titleZh: '写第一个交互：主题切换',
    titleEn: 'First interaction: theme toggle',
    goalZh: '用最小 JS 把“状态 -> 视图”跑通（class 切换 + localStorage）。',
    goalEn: 'Learn state -> UI with minimal JS (class toggle + storage).',
    tasksZh: ['在 HTML 放一个按钮（如 #themeBtn）', 'JS 里监听 click 切换 body 的 class', '把状态写进 localStorage 并在启动时恢复'],
    tasksEn: ['Add a button (e.g. #themeBtn)', 'Toggle a body class on click', 'Persist and restore with localStorage'],
    checksZh: ['刷新页面主题状态能记住', 'Console 无报错'],
    checksEn: ['Theme persists after refresh', 'No console error'],
    blocks: [
      {
        labelZh: 'main.js（主题切换最小实现）',
        labelEn: 'main.js (minimal theme toggle)',
        content: [
          'const STORAGE_KEY = \"my-site:theme\";',
          '',
          'function applyTheme(isDark) {',
          '  document.body.classList.toggle(\"is-dark\", isDark);',
          '}',
          '',
          'const saved = window.localStorage.getItem(STORAGE_KEY);',
          'applyTheme(saved === \"dark\");',
          '',
          'const btn = document.querySelector(\"#themeBtn\");',
          'if (btn) {',
          '  btn.addEventListener(\"click\", () => {',
          '    const nextIsDark = !document.body.classList.contains(\"is-dark\");',
          '    applyTheme(nextIsDark);',
          '    window.localStorage.setItem(STORAGE_KEY, nextIsDark ? \"dark\" : \"light\");',
          '  });',
          '}'
        ].join('\\n')
      }
    ]
  },
  {
    id: 'js:search',
    titleZh: '写第二个交互：搜索过滤卡片',
    titleEn: 'Second interaction: search filter',
    goalZh: '体验“输入 -> 过滤 -> 重渲染”的最常见交互链路。',
    goalEn: 'Implement the classic input -> filter -> render flow.',
    tasksZh: ['在 HTML 加 input（#q）和卡片列表容器（#list）', 'JS 用数组数据渲染卡片', '监听 input 事件过滤数据并重渲染'],
    tasksEn: ['Add input (#q) and list container (#list)', 'Render cards from an array', 'Filter on input and re-render'],
    checksZh: ['输入关键词能实时过滤', '清空后恢复全部'],
    checksEn: ['Typing filters instantly', 'Clearing restores all'],
    blocks: [
      {
        labelZh: 'main.js（最小搜索过滤）',
        labelEn: 'main.js (minimal filter)',
        content: [
          'const data = [',
          '  { id: \"a\", title: \"实验室看板\", tags: [\"learn\", \"ui\"] },',
          '  { id: \"b\", title: \"源码展示\", tags: [\"code\"] },',
          '  { id: \"c\", title: \"搜索弹窗\", tags: [\"search\", \"kbd\"] }',
          '];',
          '',
          'const $q = document.querySelector(\"#q\");',
          'const $list = document.querySelector(\"#list\");',
          '',
          'function render(items) {',
          '  if (!$list) return;',
          '  $list.innerHTML = items.map((it) => {',
          '    const tags = it.tags.map((t) => `<span class=\"tag\">${t}</span>`).join(\"\");',
          '    return `<article class=\"card\"><h2>${it.title}</h2><div class=\"tags\">${tags}</div></article>`;',
          '  }).join(\"\");',
          '}',
          '',
          'function norm(s) { return String(s || \"\").trim().toLowerCase(); }',
          'render(data);',
          '',
          'if ($q) {',
          '  $q.addEventListener(\"input\", () => {',
          '    const q = norm($q.value);',
          '    const filtered = !q ? data : data.filter((it) => norm(`${it.title} ${it.tags.join(\" \")}`).includes(q));',
          '    render(filtered);',
          '  });',
          '}'
        ].join('\n')
      }
    ]
  }
]

export const PREVIEW = {
  html: [
    '<header class=\"site-header\">',
    '  <h1>My Site</h1>',
    '  <div class=\"actions\">',
    '    <button id=\"themeBtn\" type=\"button\">Toggle Theme</button>',
    '  </div>',
    '</header>',
    '<main class=\"site-main\">',
    '  <div class=\"toolbar\">',
    '    <input id=\"q\" placeholder=\"Search...\" />',
    '  </div>',
    '  <section id=\"list\" class=\"grid\"></section>',
    '</main>'
  ].join('\\n'),
  css: [
    ':root {',
    '  --bg: #0b1020;',
    '  --panel: rgba(255,255,255,0.08);',
    '  --text: rgba(255,255,255,0.92);',
    '  --muted: rgba(255,255,255,0.66);',
    '  --border: rgba(255,255,255,0.16);',
    '}',
    '',
    'html, body { height: 100%; }',
    'body {',
    '  margin: 0;',
    '  font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;',
    '  line-height: 1.6;',
    '  color: var(--text);',
    '  background: radial-gradient(circle at 20% 10%, rgba(236,72,153,0.18), transparent 45%),',
    '    radial-gradient(circle at 90% 0%, rgba(99,102,241,0.18), transparent 45%),',
    '    var(--bg);',
    '}',
    '',
    'body.is-dark {',
    '  --bg: #060816;',
    '  --panel: rgba(255,255,255,0.06);',
    '}',
    '',
    '.site-header {',
    '  max-width: 980px;',
    '  margin: 0 auto;',
    '  padding: 22px 20px 10px;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  gap: 12px;',
    '}',
    '.site-header h1 { margin: 0; font-size: 22px; letter-spacing: -0.02em; }',
    '.actions button {',
    '  border: 1px solid var(--border);',
    '  background: rgba(255,255,255,0.08);',
    '  color: var(--text);',
    '  padding: 10px 12px;',
    '  border-radius: 12px;',
    '  cursor: pointer;',
    '}',
    '',
    '.site-main { max-width: 980px; margin: 0 auto; padding: 16px 20px 40px; }',
    '.toolbar { margin-bottom: 12px; }',
    '.toolbar input {',
    '  width: min(420px, 100%);',
    '  padding: 12px 14px;',
    '  border-radius: 14px;',
    '  border: 1px solid var(--border);',
    '  background: rgba(255,255,255,0.06);',
    '  color: var(--text);',
    '  outline: none;',
    '}',
    '.toolbar input:focus { border-color: rgba(236,72,153,0.45); }',
    '',
    '.grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 12px; }',
    '.card { border: 1px solid var(--border); background: var(--panel); border-radius: 16px; padding: 14px; }',
    '.card h2 { margin: 0 0 8px; font-size: 16px; }',
    '.tags { display: flex; flex-wrap: wrap; gap: 8px; }',
    '.tag { font-size: 12px; color: var(--muted); border: 1px solid var(--border); border-radius: 999px; padding: 6px 10px; }',
    '',
    '@media (max-width: 860px) {',
    '  .grid { grid-template-columns: 1fr; }',
    '}'
  ].join('\\n'),
  js: [
    'const THEME_KEY = \"my-site:theme\";',
    '',
    'function applyTheme(isDark) {',
    '  document.body.classList.toggle(\"is-dark\", isDark);',
    '}',
    '',
    'applyTheme(window.localStorage.getItem(THEME_KEY) === \"dark\");',
    '',
    'const themeBtn = document.querySelector(\"#themeBtn\");',
    'if (themeBtn) {',
    '  themeBtn.addEventListener(\"click\", () => {',
    '    const nextIsDark = !document.body.classList.contains(\"is-dark\");',
    '    applyTheme(nextIsDark);',
    '    window.localStorage.setItem(THEME_KEY, nextIsDark ? \"dark\" : \"light\");',
    '  });',
    '}',
    '',
    'const data = [',
    '  { id: \"a\", title: \"实验室看板\", tags: [\"learn\", \"ui\"] },',
    '  { id: \"b\", title: \"源码展示\", tags: [\"code\"] },',
    '  { id: \"c\", title: \"搜索弹窗\", tags: [\"search\", \"kbd\"] }',
    '];',
    '',
    'const $q = document.querySelector(\"#q\");',
    'const $list = document.querySelector(\"#list\");',
    '',
    'function norm(s) { return String(s || \"\").trim().toLowerCase(); }',
    '',
    'function render(items) {',
    '  if (!$list) return;',
    '  $list.innerHTML = items.map((it) => {',
    '    const tags = it.tags.map((t) => `<span class=\"tag\">${t}</span>`).join(\"\");',
    '    return `<article class=\"card\"><h2>${it.title}</h2><div class=\"tags\">${tags}</div></article>`;',
    '  }).join(\"\");',
    '}',
    '',
    'render(data);',
    '',
    'if ($q) {',
    '  $q.addEventListener(\"input\", () => {',
    '    const q = norm($q.value);',
    '    const filtered = !q ? data : data.filter((it) => norm(`${it.title} ${it.tags.join(\" \")}`).includes(q));',
    '    render(filtered);',
    '  });',
    '}'
  ].join('\\n')
}
