import type { TutorialStep } from './tutorialStepsLoader'

export const STEPS: TutorialStep[] = [
  {
    id: 'css:base',
    titleZh: '先把“可读性”拉起来',
    titleEn: 'Improve readability first',
    goalZh: '优先解决字体、间距、背景，让页面看起来像个站。',
    goalEn: 'Start with typography/spacing so the page feels like a site.',
    tasksZh: ['写基础样式：font、line-height、背景', '给 header/main 做间距', '让卡片有边框/圆角/阴影'],
    tasksEn: ['Set font/line-height/background', 'Add spacing for header/main', 'Style card with border/radius/shadow'],
    checksZh: ['页面不再是默认样式', '不同区域有清晰层级'],
    checksEn: ['Page is no longer browser-default', 'Clear visual hierarchy'],
    blocks: [
      {
        labelZh: 'styles.css（基础可读性）',
        labelEn: 'styles.css (baseline)',
        content: [
          ':root {',
          '  --bg: #0b1020;',
          '  --panel: rgba(255,255,255,0.08);',
          '  --text: rgba(255,255,255,0.92);',
          '  --muted: rgba(255,255,255,0.66);',
          '  --border: rgba(255,255,255,0.16);',
          '}',
          '',
          'html, body { height: 100%; }',
          'body {',
          '  margin: 0;',
          '  font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;',
          '  line-height: 1.6;',
          '  color: var(--text);',
          '  background: radial-gradient(circle at 20% 10%, rgba(236,72,153,0.18), transparent 45%),',
          '    radial-gradient(circle at 90% 0%, rgba(99,102,241,0.18), transparent 45%),',
          '    var(--bg);',
          '}',
          '',
          '.site-header { padding: 28px 20px 10px; max-width: 980px; margin: 0 auto; }',
          '.site-header h1 { margin: 0; font-size: 28px; letter-spacing: -0.02em; }',
          '.subtitle { margin: 6px 0 0; color: var(--muted); }',
          '',
          '.site-main { max-width: 980px; margin: 0 auto; padding: 16px 20px 40px; }',
          '.card {',
          '  border: 1px solid var(--border);',
          '  background: var(--panel);',
          '  border-radius: 16px;',
          '  padding: 16px;',
          '  box-shadow: 0 22px 70px rgba(0,0,0,0.30);',
          '}',
          '.card h2 { margin: 0 0 8px; font-size: 18px; }',
          '.card p { margin: 0; color: var(--muted); }'
        ].join('\n')
      }
    ]
  },
  {
    id: 'css:layout',
    titleZh: '加一个“导航 + 内容”的布局',
    titleEn: 'Add nav + content layout',
    goalZh: '把页面拆成左侧导航与右侧内容，模拟真实站点框架。',
    goalEn: 'Split into sidebar + main to resemble a real layout.',
    tasksZh: ['在 HTML 里加一个 sidebar 容器', '用 CSS Grid 或 Flex 做两栏', '给移动端一个折叠/堆叠方案'],
    tasksEn: ['Add a sidebar container in HTML', 'Use Grid/Flex for two columns', 'Make it responsive for mobile'],
    checksZh: ['宽屏是两栏', '窄屏下内容不会挤坏'],
    checksEn: ['Two columns on wide screens', 'No layout break on narrow screens'],
    blocks: [
      {
        labelZh: 'HTML（增加 sidebar 容器）',
        labelEn: 'HTML (add sidebar)',
        content: [
          '<main class="site-main layout">',
          '  <aside class="sidebar">',
          '    <div class="sidebar-title">导航</div>',
          '    <a class="nav-item is-active" href="#">最近</a>',
          '    <a class="nav-item" href="#">文件</a>',
          '    <a class="nav-item" href="#">实验室</a>',
          '  </aside>',
          '  <section class="content">',
          '    <section class="card">',
          '      <h2>第一张卡片</h2>',
          '      <p>现在我们有“站点骨架 + 两栏布局”。</p>',
          '    </section>',
          '  </section>',
          '</main>'
        ].join('\n')
      },
      {
        labelZh: 'CSS（两栏 + 响应式）',
        labelEn: 'CSS (two columns + responsive)',
        content: [
          '.layout {',
          '  display: grid;',
          '  grid-template-columns: 240px 1fr;',
          '  gap: 16px;',
          '}',
          '.sidebar {',
          '  border: 1px solid var(--border);',
          '  background: rgba(255,255,255,0.06);',
          '  border-radius: 16px;',
          '  padding: 14px;',
          '}',
          '.sidebar-title { font-weight: 800; font-size: 12px; color: var(--muted); margin-bottom: 10px; }',
          '.nav-item {',
          '  display: block;',
          '  padding: 10px 12px;',
          '  border-radius: 12px;',
          '  color: var(--text);',
          '  text-decoration: none;',
          '  border: 1px solid transparent;',
          '}',
          '.nav-item:hover { border-color: rgba(255,255,255,0.20); background: rgba(255,255,255,0.06); }',
          '.nav-item.is-active { border-color: rgba(236,72,153,0.35); background: rgba(236,72,153,0.12); }',
          '',
          '@media (max-width: 860px) {',
          '  .layout { grid-template-columns: 1fr; }',
          '}'
        ].join('\n')
      }
    ]
  }
]

export const PREVIEW = {
  html: [
    '<header class="site-header">',
    '  <h1>My Site</h1>',
    '  <p class="subtitle">Two-column layout preview</p>',
    '</header>',
    '<main class="site-main layout">',
    '  <aside class="sidebar">',
    '    <div class="sidebar-title">导航</div>',
    '    <a class="nav-item is-active" href="#">最近</a>',
    '    <a class="nav-item" href="#">文件</a>',
    '    <a class="nav-item" href="#">实验室</a>',
    '  </aside>',
    '  <section class="content">',
    '    <section class="card">',
    '      <h2>第一张卡片</h2>',
    '      <p>现在我们有“站点骨架 + 两栏布局”。</p>',
    '    </section>',
    '  </section>',
    '</main>'
  ].join('\n'),
  css: [
    ':root {',
    '  --bg: #0b1020;',
    '  --panel: rgba(255,255,255,0.08);',
    '  --text: rgba(255,255,255,0.92);',
    '  --muted: rgba(255,255,255,0.66);',
    '  --border: rgba(255,255,255,0.16);',
    '}',
    '',
    'html, body { height: 100%; }',
    'body {',
    '  margin: 0;',
    '  font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;',
    '  line-height: 1.6;',
    '  color: var(--text);',
    '  background: radial-gradient(circle at 20% 10%, rgba(236,72,153,0.18), transparent 45%),',
    '    radial-gradient(circle at 90% 0%, rgba(99,102,241,0.18), transparent 45%),',
    '    var(--bg);',
    '}',
    '',
    '.site-header { padding: 22px 20px 10px; max-width: 980px; margin: 0 auto; }',
    '.site-header h1 { margin: 0; font-size: 22px; letter-spacing: -0.02em; }',
    '.subtitle { margin: 6px 0 0; color: var(--muted); }',
    '',
    '.site-main { max-width: 980px; margin: 0 auto; padding: 16px 20px 40px; }',
    '.layout { display: grid; grid-template-columns: 240px 1fr; gap: 16px; }',
    '.sidebar { border: 1px solid var(--border); background: rgba(255,255,255,0.06); border-radius: 16px; padding: 14px; }',
    '.sidebar-title { font-weight: 800; font-size: 12px; color: var(--muted); margin-bottom: 10px; }',
    '.nav-item { display:block; padding:10px 12px; border-radius:12px; color: var(--text); text-decoration:none; border: 1px solid transparent; }',
    '.nav-item:hover { border-color: rgba(255,255,255,0.20); background: rgba(255,255,255,0.06); }',
    '.nav-item.is-active { border-color: rgba(236,72,153,0.35); background: rgba(236,72,153,0.12); }',
    '.content { min-width: 0; }',
    '.card { border: 1px solid var(--border); background: var(--panel); border-radius: 16px; padding: 16px; box-shadow: 0 22px 70px rgba(0,0,0,0.30); }',
    '.card h2 { margin: 0 0 8px; font-size: 16px; }',
    '.card p { margin: 0; color: var(--muted); }',
    '',
    '@media (max-width: 860px) {',
    '  .layout { grid-template-columns: 1fr; }',
    '}'
  ].join('\n'),
  js: ''
}

